### PR TITLE
Check if $post is instance of \WP_Post

### LINKED ISSUE #76: "Notice: Function post_type was called incorrectly" on new WooCommerce orders edit screen
### Describe the bug

If WooCommerce is active and using the new High Performance order Tables, this plugin throws several notices on the order edit screen (wp-admin/admin.php?page=wc-orders&action=edit&id=12345)

`Notice: Function post_type was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('load-woocommerce_page_wc-orders'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Internal\Admin\Orders\PageController->__call, call_user_func_array, Automattic\WooCommerce\Internal\Admin\Orders\PageController->handle_load_page_action, Automattic\WooCommerce\Internal\Admin\Orders\PageController->setup_action_edit_order, Automattic\WooCommerce\Internal\Admin\Orders\PageController->prepare_order_edit_form, Automattic\WooCommerce\Internal\Admin\Orders\Edit->setup, do_action('add_meta_boxes'), WP_Hook->do_action, WP_Hook->apply_filters, TenUp\ContentConnect\UI\MetaBox->add_meta_boxes, apply_filters('tenup_content_connect_post_relationship_data'), WP_Hook->apply_filters, TenUp\ContentConnect\UI\PostToPost->filter_data, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in /Users/marcoalmeida/Documents/Websites/_local/wordpress-testing/app/public/wp-includes/functions.php on line 6078`

### Steps to Reproduce

1. Activate this plugin
2. Activate WooCommerce
3. Activate HPOS on WooCommerce
4. Got to a order edit screen and see the notices

### Screenshots, screen recording, code snippet

image

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by s3rgiosan**
### Description of the Change

Closes #76

### Credits

Props @webdados, @s3rgiosan 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by s3rgiosan** [comment]
@jeffpaul @rickalee for visibility

**Comment by rickalee** [comment]
Looks good to me. @s3rgiosan cc @jeffpaul ✅

**Comment by s3rgiosan** [comment]
@jeffpaul Let me know if you need anything from me to get this merged and released?

**Comment by jeffpaul** [comment]
@s3rgiosan there's a handful of other items in the [1.6.0 milestone](https://github.com/10up/wp-content-connect/milestone/2), if you're able to help review those to see which are good to merge then we can get all that bundled up and released (or punt the rest to a 1.7.0 release)

**Pull request merged**
